#!/usr/bin/env bash
# -------------------------------------------------------
# Script to install android tools for 26.04
#
# 20/03/2026, v1.0 - Migration from 24.04
#
# -------------------------------------------------------

# adb and fastboot
logger "android - adb and fastboot"
sudo apt -y install android-tools-adb android-tools-fastboot

# APK thumbnailer
logger "android - APK thumbnailer"
wget https://github.com/NicolasBernaerts/ubuntu-scripts/raw/refs/heads/master/thumbnailer/apk/apk-thumbnailer-install.sh
if [ -f ./apk-thumbnailer-install.sh ]
then
  chmod +x ./apk-thumbnailer-install.sh
  ./apk-thumbnailer-install.sh
  rm ./apk-thumbnailer-install.sh
fi

# file manager APK extensions
logger "android - file manager APK extensions"
wget https://github.com/NicolasBernaerts/ubuntu-scripts/raw/refs/heads/master/nautilus/nautilus-apk-install.sh
if [ -f ./nautilus-apk-install.sh ]
then
  chmod +x ./nautilus-apk-install.sh
  ./nautilus-apk-install.sh
  rm ./nautilus-apk-install.sh
fi

# android scrcpy utility
logger "android - scrcpy utility"
wget -O scrcpy.tar.gz https://github.com/Genymobile/scrcpy/releases/download/v3.3.4/scrcpy-linux-x86_64-v3.3.4.tar.gz
sudo mkdir /usr/local/bin/scrcpy
sudo tar -xvf scrcpy.tar.gz -C /usr/local/bin --strip-components 1
sudo mv /usr/local/bin/icon.png /usr/share/icons/scrcpy.png
rm scrcpy.tar.gz
sudo wget -O /usr/share/applications/scrcpy.desktop https://github.com/NicolasBernaerts/ubuntu-scripts/raw/refs/heads/master/android/scrcpy.desktop
